version: "2"
services:
  burrow:
    image: magnetme/burrow
    volumes:
      - ${PWD}/burrow-config:/etc/burrow
      - ${PWD}/tmp:/var/tmp/burrow
    ports:
      - 8000:8000

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/local
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test-topic:2:1,test-topic2:1:1,test-topic3:1:1"

  datadog-agent:
    image: datadog/docker-dd-agent
    command: echo STOPPED
    environment:
      API_KEY: 123
    volumes:
      - ${PWD}/test.py:/test.py
      - ${PWD}/checks.d:/etc/dd-agent/checks.d
      - ${PWD}/conf.d:/etc/dd-agent/conf.d
